### ISSUE TITLE
Deal of the day

### ISSUE THREAD

**Issue by CaddyDz** [01Eva/test1#38]
* Get the highest discount from the ones created today
```php
$discount = Discount::whereDay(today())->orderBy('percentage', 'asc')->first();
```
* Get the product associated with that discount
```php
$product => $discount->product;
```
* Show that product in the deal of the day section
* Make a countdown using the expiry date of that discount

**Comment by CaddyDz** [comment]
// cc @01Eva

**Comment by 01Eva** [comment]
i think it's a good idea, i approve of this method
