### ISSUE TITLE
order orders by status

### ISSUE THREAD

**Issue by 01Eva** [01Eva/test1#8]
### Orders: 

- nouvelle
- confirmé
- en attente
- rejeté

**Comment by CaddyDz** [comment]
What do you mean by `nouvelle`?

**Comment by 01Eva** [comment]
awaiting for review are new orders that haven't been reviewed right?

**Comment by CaddyDz** [comment]
Yes, not necessarily the newest tho, workers get to choose to review high priority orders first despite creation date

**Comment by 01Eva** [comment]
yes true

**Comment by CaddyDz** [comment]
So we have multiple options here, we can make the status sortable which gives the user the abillity to order by status
```php
Badge::make('Status')
	->options([
		'pending' => __('Awaiting review'),
		'validated' => __('Validated'),
		'rejected' => __('Refused'),
		'suspended' => __('On hold'),
	])
	->colors([
		'pending' => '#64cedb',
		'validated' => '#42d6a9',
		'suspended' => '#000',
		'rejected' => '#ca404d',
	])->displayUsingLabels()
	->sortable(), // <--- Here
```

**Comment by 01Eva** [comment]
can we also get them sorted by workers? like when a worker put on hold an order we know he's the one that did it?

**Comment by CaddyDz** [comment]
> can we also get them sorted by workers? like when a worker put on hold an order we know he's the one that did it?

Yes, we have two approaches here, this is for another issue tho 😛

**Comment by 01Eva** [comment]
alright! now do they show sorted under the "commande"?

**Comment by CaddyDz** [comment]
not by default, must click the status title to sort

**Comment by CaddyDz** [comment]
Now you can also filter by status

![image](https://user-images.githubusercontent.com/13698160/91208091-90e2fd00-e701-11ea-9962-d8a05d49a069.png)

**Comment by 01Eva** [comment]
i see ! i like it

**Comment by CaddyDz** [comment]
Here's how we apply default ordering
```php
protected static function applyOrderings($query, array $orderings)
{
	if (empty($orderings)) {
		// This is your default order
		$orderings['status'] = 'asc';
	}
	return parent::applyOrderings($query, $orderings);
}
```

**Comment by 01Eva** [comment]
how does this default ordering show on the web page

**Comment by CaddyDz** [comment]
Ascending status by alphabetic order

i.e starts with Awaiting Review and going forward

**Comment by 01Eva** [comment]
ohhh, i don't think i's necessary they should be ordered by order time by default khir

**Comment by CaddyDz** [comment]
Alright, that was the default behavior anyway

**Comment by 01Eva** [comment]
great

**Comment by 01Eva** [comment]
u pushed all changed?

**Comment by CaddyDz** [comment]
Yes, do we need lenses as well as filters? or are filters enough?

**Comment by 01Eva** [comment]
i really didn't understand

**Comment by CaddyDz** [comment]
Can filter further like this, where we can get rid of the status field because it's redundant

![image](https://user-images.githubusercontent.com/13698160/91214139-93962000-e70a-11ea-8dd5-eb1ad44a602f.png)

**Comment by 01Eva** [comment]
i think both are fine

**Comment by CaddyDz** [comment]
Alright, pushed in #10
